"use client";
import { useEffect, useRef, useState } from "react";
import { PREFECTURE_ORIGINS, prefectureOrigin, type OriginMode, type UserOrigin } from "../../../../../../packages/shared/userOrigin";

type Candidate = { place_id: string; name: string | null; lat: number; lng: number; type?: string };
export default function OriginSelector({ origin, onChange, onUseDevice, deviceError }: { origin: UserOrigin | null; onChange: (value: UserOrigin | null) => void; onUseDevice: () => void; deviceError?: string | null }) {
  const [mode, setMode] = useState<OriginMode>(origin?.source === "device" ? "device" : origin?.source === "prefecture" ? "prefecture" : origin ? "manual" : "none");
  const [query, setQuery] = useState(""); const [items, setItems] = useState<Candidate[]>([]); const [status, setStatus] = useState<"idle"|"searching"|"empty"|"error">("idle");
  const requestId = useRef(0);
  useEffect(() => { if (mode !== "manual" || query.trim().length < 2) { setItems([]); setStatus("idle"); return; } const id=++requestId.current; const timer=setTimeout(async()=>{ setStatus("searching"); try { const res=await fetch(`/api/geocodes/search/?q=${encodeURIComponent(query.trim())}&limit=5&lang=ja`); if(!res.ok) throw new Error(); const data=await res.json(); if(id!==requestId.current)return; const next=Array.isArray(data.items)?data.items:[]; setItems(next); setStatus(next.length?"idle":"empty"); } catch { if(id===requestId.current){setItems([]);setStatus("error");} } },400); return()=>clearTimeout(timer); },[mode,query]);
  const switchMode=(next:OriginMode)=>{ requestId.current++; setMode(next); onChange(null); setItems([]); if(next==="device") onUseDevice(); };
  return <div className="space-y-2"><p className="text-[11px] font-medium text-stone-500">出発地点</p><div className="grid grid-cols-2 gap-2">{[["device","現在地を使用"],["manual","駅名・住所から指定"],["prefecture","都道府県から指定"],["disabled","方位情報を使用しない"]].map(([value,label])=><button key={value} type="button" onClick={()=>switchMode(value as OriginMode)} className={`rounded-xl border px-2 py-2 text-xs ${mode===value?"border-emerald-300 bg-emerald-50":"border-stone-200 bg-white"}`}>{label}</button>)}</div>
  {mode==="manual"?<div><input aria-label="駅名または住所" value={query} onChange={e=>{setQuery(e.target.value);onChange(null);}} placeholder="駅名または住所を入力" className="w-full rounded-xl border border-stone-200 px-3 py-2 text-sm" />{status==="searching"?<p className="text-xs text-stone-500">検索中…</p>:null}{status==="empty"?<p className="text-xs text-stone-500">候補が見つかりません。相談はそのまま続けられます。</p>:null}{status==="error"?<p className="text-xs text-rose-600">検索できませんでした。相談はそのまま続けられます。</p>:null}<div>{items.map(item=><button type="button" key={item.place_id} onClick={()=>{onChange({latitude:item.lat,longitude:item.lng,source:item.type==="station"?"station":"address",displayName:item.name??query,accuracy:"precise"});setItems([]);}} className="block w-full border-b border-stone-100 px-2 py-2 text-left text-xs">{item.name}</button>)}</div></div>:null}
  {mode==="prefecture"?<div><select aria-label="都道府県" className="w-full rounded-xl border border-stone-200 px-3 py-2 text-sm" value={origin?.source==="prefecture"?origin.displayName:""} onChange={e=>onChange(prefectureOrigin(e.target.value))}><option value="">都道府県を選択</option>{PREFECTURE_ORIGINS.map(p=><option key={p.name}>{p.name}</option>)}</select>{origin?.source==="prefecture"?<p className="text-xs text-stone-500">{origin.displayName}のおおよその位置を出発地点として使用します。方位は参考情報として表示されます。</p>:null}</div>:null}
  {deviceError&&mode==="device"?<p className="text-xs text-stone-600">{deviceError} 手動入力を選択できます。</p>:null}{origin?<p className="text-xs text-emerald-700">設定中：{origin.displayName??"現在地"}</p>:null}</div>;
}
