export const cardSizes = {
  borderWidth: 1,
  radiusSm: 12,
  radiusMd: 16,
  radiusLg: 20,
  pillRadius: 999,
  carouselWidth: 220,
  carouselWidthLg: 256,
  imageSm: 64,
  imageRadius: 12,
  cardPaddingSm: 12,
  cardPaddingMd: 14,
  cardPaddingLg: 18,
  rankBadgeSize: 32,
  skeletonWidth: 160,
  skeletonRadius: 14,
  shimmerRadius: 8,
} as const;
