from __future__ import annotations

import logging

from dataclasses import dataclass
from typing import Optional

from django.conf import settings
from django.db import connection, transaction
from django.utils import timezone

from temples.models import FeatureUsage, ConciergeUsage

from temples.services.plan_service import PlanContext
from temples.services.quota_policy import get_feature_policy

log = logging.getLogger(__name__)


def ensure_feature_usage_table() -> None:
    table_name = FeatureUsage._meta.db_table
    user_table_name = FeatureUsage._meta.get_field("user").remote_field.model._meta.db_table

    if connection.vendor == "postgresql":
        sql_statements = [
            f"""
            CREATE TABLE IF NOT EXISTS {table_name} (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope varchar(16) NOT NULL,
                anon_id varchar(64) NOT NULL DEFAULT '',
                feature varchar(32) NOT NULL,
                count integer NOT NULL DEFAULT 0 CHECK (count >= 0),
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
                user_id bigint NULL REFERENCES {user_table_name}(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT chk_feature_usage_scope_target CHECK (
                    (scope = 'user' AND user_id IS NOT NULL AND anon_id = '')
                    OR
                    (scope = 'anonymous' AND user_id IS NULL AND anon_id > '')
                )
            )
            """,
            f"CREATE INDEX IF NOT EXISTS temples_fea_scope_16bb7d_idx ON {table_name} (scope, feature)",
            f"CREATE INDEX IF NOT EXISTS temples_fea_user_id_ed3ce9_idx ON {table_name} (user_id, feature)",
            f"CREATE INDEX IF NOT EXISTS temples_fea_anon_id_6f0176_idx ON {table_name} (anon_id, feature)",
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_user_feature
            ON {table_name} (user_id, feature)
            WHERE scope = 'user' AND user_id IS NOT NULL
            """,
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_anon_feature
            ON {table_name} (anon_id, feature)
            WHERE scope = 'anonymous' AND anon_id > ''
            """,
        ]
    else:
        sql_statements = [
            f"""
            CREATE TABLE IF NOT EXISTS {table_name} (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                scope varchar(16) NOT NULL,
                anon_id varchar(64) NOT NULL DEFAULT '',
                feature varchar(32) NOT NULL,
                count integer unsigned NOT NULL DEFAULT 0 CHECK (count >= 0),
                created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                user_id bigint NULL REFERENCES {user_table_name}(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT chk_feature_usage_scope_target CHECK (
                    (scope = 'user' AND user_id IS NOT NULL AND anon_id = '')
                    OR
                    (scope = 'anonymous' AND user_id IS NULL AND anon_id > '')
                )
            )
            """,
            f"CREATE INDEX IF NOT EXISTS temples_fea_scope_16bb7d_idx ON {table_name} (scope, feature)",
            f"CREATE INDEX IF NOT EXISTS temples_fea_user_id_ed3ce9_idx ON {table_name} (user_id, feature)",
            f"CREATE INDEX IF NOT EXISTS temples_fea_anon_id_6f0176_idx ON {table_name} (anon_id, feature)",
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_user_feature
            ON {table_name} (user_id, feature)
            WHERE scope = 'user' AND user_id IS NOT NULL
            """,
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_anon_feature
            ON {table_name} (anon_id, feature)
            WHERE scope = 'anonymous' AND anon_id > ''
            """,
        ]

    with connection.cursor() as cursor:
        for statement in sql_statements:
            cursor.execute(statement)


@dataclass(frozen=True)
class QuotaStatus:
    allowed: bool
    feature: str
    plan: str
    used: int
    limit: Optional[int]
    remaining: Optional[int]
    unlimited: bool
    reason_code: Optional[str] = None


def get_used_count(plan_context: PlanContext, feature: str) -> int:

    current_count = 0
    feature_obj = None

    if plan_context.plan == "anonymous":
        obj, created = FeatureUsage.objects.get_or_create(
            scope="anonymous",
            anon_id=plan_context.anon_id,
            feature=feature,
            defaults={"count": 0},
        )
        feature_obj = obj
        current_count = obj.count

        log.warning(
            "[quota/read][feature] created=%s scope=%s feature=%s count=%r",
            created,
            obj.scope,
            obj.feature,
            obj.count,
        )
    else:
        obj, created = FeatureUsage.objects.get_or_create(
            scope="user",
            user_id=plan_context.user_id,
            feature=feature,
            defaults={"count": 0},
        )
        feature_obj = obj
        current_count = obj.count

        log.warning(
            "[quota/read][feature] created=%s scope=%s feature=%s count=%r",
            created,
            obj.scope,
            obj.feature,
            obj.count,
        )

    legacy = None

    # 旧 concierge 日次usageとの互換
    if feature == "concierge" and plan_context.user_id:
        legacy = (
            ConciergeUsage.objects.filter(
                user_id=plan_context.user_id,
                date=timezone.localdate(),
            )
            .values_list("count", flat=True)
            .first()
        )
        if legacy is not None:
            current_count = max(current_count, legacy)

    log.warning(
        "[quota/read][final] plan=%s feature=%s feature_count=%r legacy_count=%r used=%r",
        plan_context.plan,
        feature,
        getattr(feature_obj, "count", None),
        legacy,
        current_count,
    )

    return current_count


def check_quota(plan_context: PlanContext, feature: str) -> QuotaStatus:
    policy = get_feature_policy(plan_context.plan, feature)

    if policy.get("unlimited"):
        log.warning(
            "[quota/check] plan=%s feature=%s unlimited=1",
            plan_context.plan,
            feature,
        )
        return QuotaStatus(
            allowed=True,
            feature=feature,
            plan=plan_context.plan,
            used=0,
            limit=None,
            remaining=None,
            unlimited=True,
        )

    used = get_used_count(plan_context, feature)

    limit = policy["limit"]
    if feature == "concierge" and plan_context.plan == "free":
        limit = int(getattr(settings, "CONCIERGE_DAILY_FREE_LIMIT", limit))

    remaining = max(limit - used, 0)

    log.warning(
        "[quota/check] plan=%s feature=%s used=%r limit=%r remaining=%r allowed=%s",
        plan_context.plan,
        feature,
        used,
        limit,
        remaining,
        used < limit,
    )

    return QuotaStatus(
        allowed=used < limit,
        feature=feature,
        plan=plan_context.plan,
        used=used,
        limit=limit,
        remaining=remaining,
        unlimited=False,
        reason_code=None if used < limit else "LIMIT_REACHED",
    )


@transaction.atomic
def consume_quota(plan_context: PlanContext, feature: str, amount: int = 1) -> None:

    policy = get_feature_policy(plan_context.plan, feature)

    if policy.get("unlimited"):
        log.warning(
            "[quota/consume] skipped_unlimited=1 plan=%s feature=%s",
            plan_context.plan,
            feature,
        )
        return

    if plan_context.plan == "anonymous":
        obj, created = FeatureUsage.objects.select_for_update().get_or_create(
            scope="anonymous",
            anon_id=plan_context.anon_id,
            feature=feature,
            defaults={"count": 0},
        )
    else:
        obj, created = FeatureUsage.objects.select_for_update().get_or_create(
            scope="user",
            user_id=plan_context.user_id,
            feature=feature,
            defaults={"count": 0},
        )

    before_count = obj.count
    obj.count += amount
    obj.save(update_fields=["count", "updated_at"])
    obj.refresh_from_db()

    log.warning(
        "[quota/consume][feature] created=%s scope=%s feature=%s before=%r after=%r",
        created,
        obj.scope,
        obj.feature,
        before_count,
        obj.count,
    )

    # 旧 concierge 日次usageとの互換書き込み
    if feature == "concierge" and plan_context.user_id:
        legacy_usage, legacy_created = ConciergeUsage.objects.select_for_update().get_or_create(
            user_id=plan_context.user_id,
            date=timezone.localdate(),
            defaults={"count": 0},
        )

        legacy_before = legacy_usage.count
        legacy_limit = int(getattr(settings, "CONCIERGE_DAILY_FREE_LIMIT", 5))
        legacy_usage.count = min(legacy_usage.count + amount, legacy_limit)
        legacy_usage.save(update_fields=["count"])
        legacy_usage.refresh_from_db()

        log.warning(
            "[quota/consume][legacy] created=%s date=%s before=%r after=%r",
            legacy_created,
            timezone.localdate(),
            legacy_before,
            legacy_usage.count,
        )
