# Generated by Django 5.2.8 on 2026-08-05 03:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import temples.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0007_shrine_history_theme_shrine_idx_shrine_history_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('action_started', 'Action started'), ('action_completed', 'Action completed')], db_index=True, max_length=32)),
                ('action_suggestion_id', models.CharField(db_index=True, max_length=128)),
                ('history_theme', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('action_category', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciergeRecommendationClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrine_id', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, default='', max_length=255)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temples_concierge_recommendation_click_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_km', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('min_lng', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('max_lng', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_page_token', models.CharField(blank=True, default='', max_length=256)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('anonymous', 'Anonymous'), ('user', 'User')], max_length=16)),
                ('anon_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('feature', models.CharField(choices=[('concierge', 'Concierge'), ('favorite', 'Favorite'), ('goshuin_upload', 'Goshuin Upload')], max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'place_cache',
            },
        ),
        migrations.CreateModel(
            name='PlacesSeed',
            fields=[
                ('seed_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pref_code', models.CharField(blank=True, default='', max_length=2)),
                ('pref', models.CharField(blank=True, default='', max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places_seed',
            },
        ),
        migrations.CreateModel(
            name='ProductionDataBootstrapRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=100)),
                ('args', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShrineDeity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('canonical_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('primary', 'primary'), ('enshrined', 'enshrined'), ('secondary', 'secondary'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShrineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('official_origin', 'official_origin'), ('founding', 'founding'), ('historical_event', 'historical_event'), ('tradition', 'tradition'), ('regional_context', 'regional_context'), ('editorial_summary', 'editorial_summary')], max_length=32)),
                ('title', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('content', models.TextField(validators=[temples.models._validate_not_blank])),
                ('period_text', models.CharField(blank=True, default='', help_text='推定年代等、幅を持つ期間表現（例: 8世紀頃）。確定日はevent_dateを使う。', max_length=255)),
                ('event_date', models.DateField(blank=True, help_text='確定している場合のみ設定する。', null=True)),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shrine histories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShrineInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('detail_view', 'Detail view'), ('route_open', 'Route open'), ('shrine_card_click', 'Shrine card click')], db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShrineKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('shrine_official', 'shrine_official'), ('government', 'government'), ('cultural_property', 'cultural_property'), ('academic', 'academic'), ('museum_or_archive', 'museum_or_archive'), ('local_history', 'local_history'), ('tourism_official', 'tourism_official'), ('secondary_editorial', 'secondary_editorial'), ('user_observation', 'user_observation'), ('internal_research', 'internal_research')], max_length=32)),
                ('title', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('bibliography', models.TextField(blank=True, default='')),
                ('accessed_at', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShrineReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_theme', models.CharField(blank=True, default='', help_text='保存時点の history_theme スナップショット', max_length=32)),
                ('prompt', models.TextField(blank=True, default='')),
                ('answer', models.TextField()),
                ('mood_before', models.CharField(blank=True, default='', max_length=50)),
                ('mood_after', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShrineSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('goriyaku_tags', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shrinedeities',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shrinedeities',
            name='deity',
        ),
        migrations.RemoveField(
            model_name='shrinedeities',
            name='shrine',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='deities',
        ),
        migrations.AlterModelOptions(
            name='deity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='goriyakutag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='goshuin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shrine',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visited_at']},
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visit_visited_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visit_shrine_visited_idx',
        ),
        migrations.RenameIndex(
            model_name='placeref',
            new_name='place_ref_name_63fd60_idx',
            old_name='place_ref_name_idx',
        ),
        migrations.RenameIndex(
            model_name='placeref',
            new_name='place_ref_synced__310299_idx',
            old_name='place_ref_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='shrine',
            new_name='temples_shr_name_jp_2d623e_idx',
            old_name='idx_shrine_name_jp',
        ),
        migrations.RenameIndex(
            model_name='shrine',
            new_name='temples_shr_updated_7a628a_idx',
            old_name='idx_shrine_updated_at',
        ),
        migrations.RemoveField(
            model_name='deity',
            name='name_romaji',
        ),
        migrations.AddField(
            model_name='shrine',
            name='visit_style_tags',
            field=models.JSONField(blank=True, default=list, help_text="参拝スタイルタグ: ['quiet','nature','classic'] など"),
        ),
        migrations.AddField(
            model_name='visit',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='参拝のきっかけとなった相談スレッド（Recommendation Snapshotへの接続キー）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='temples.conciergethread'),
        ),
        migrations.AlterField(
            model_name='deity',
            name='aliases',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='deity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deity',
            name='kana',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='deity',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='deity',
            name='wiki_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='goriyakutag',
            name='category',
            field=models.CharField(choices=[('ご利益', '願望・テーマ別'), ('神格', '祭神の種類'), ('地域', '地域や役割')], default='ご利益', max_length=50),
        ),
        migrations.AlterField(
            model_name='goriyakutag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goriyakutag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='goshuin',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='goshuin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goshuin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goshuin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='astro_elements',
            field=models.JSONField(blank=True, default=list, help_text="西洋占星術エレメント: ['火','土','風','水']"),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='element',
            field=models.CharField(blank=True, help_text='五行属性: 木火土金水', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='goriyaku',
            field=models.TextField(blank=True, default='', help_text='ご利益（自由メモ）', null=True),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='kind',
            field=models.CharField(choices=[('shrine', '神社'), ('temple', '寺院')], db_index=True, default='shrine', max_length=10),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='kyusei',
            field=models.CharField(blank=True, choices=[('一白水星', '一白水星'), ('二黒土星', '二黒土星'), ('三碧木星', '三碧木星'), ('四緑木星', '四緑木星'), ('五黄土星', '五黄土星'), ('六白金星', '六白金星'), ('七赤金星', '七赤金星'), ('八白土星', '八白土星'), ('九紫火星', '九紫火星')], help_text='九星（例: 九紫火星）', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='name_jp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='name_romaji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='sajin',
            field=models.TextField(blank=True, default='', help_text='祭神', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='temples.shrine'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], default='added', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='conciergethread',
            index=models.Index(fields=['anonymous_id', 'last_message_at'], name='temples_con_anonymo_b4584d_idx'),
        ),
        migrations.AddIndex(
            model_name='goriyakutag',
            index=models.Index(fields=['category', 'name'], name='temples_gor_categor_761fec_idx'),
        ),
        migrations.AddConstraint(
            model_name='conciergethread',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('anonymous_id__isnull', False), _connector='OR'), name='concierge_thread_user_or_anonymous_required'),
        ),
        migrations.AddConstraint(
            model_name='shrine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='chk_lat_lng_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='shrine',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False), ('place_ref__isnull', True)), fields=('name_jp', 'address', 'location'), name='uq_shrine_name_loc'),
        ),
        migrations.AddConstraint(
            model_name='shrine',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True), ('place_ref__isnull', True)), fields=('name_jp', 'address'), name='uq_shrine_name_addr_when_loc_null'),
        ),
        migrations.AddConstraint(
            model_name='shrine',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='chk_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='shrine',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='chk_lng_range'),
        ),
        migrations.AlterModelTable(
            name='deity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goriyakutag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shrine',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visit',
            table=None,
        ),
        migrations.AddField(
            model_name='actionevent',
            name='shrine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_events', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='actionevent',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_events', to='temples.conciergethread'),
        ),
        migrations.AddField(
            model_name='actionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciergehistory',
            name='shrine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_histories', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='conciergehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciergerecommendationclicklog',
            name='recommendation_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='temples.conciergerecommendationlog'),
        ),
        migrations.AddField(
            model_name='conciergerecommendationclicklog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_click_logs', to='temples.conciergethread'),
        ),
        migrations.AddField(
            model_name='conciergerecommendationclicklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_recommendation_click_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='crawltile',
            index=models.Index(fields=['status', 'last_crawled_at'], name='temples_cra_status_6524a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawltile',
            constraint=models.UniqueConstraint(fields=('step_km', 'min_lat', 'min_lng', 'max_lat', 'max_lng'), name='uniq_crawltile_step_bbox'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='shrine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shrines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='placecache',
            index=models.Index(fields=['fetched_at'], name='place_cache_fetched_db467c_idx'),
        ),
        migrations.CreateModel(
            name='PlacesSeedState',
            fields=[
                ('seed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to='temples.placesseed')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('running', 'Running')], db_index=True, default='never', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_requests_used', models.IntegerField(default=0)),
                ('last_upserted', models.IntegerField(default=0)),
                ('last_fetched', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_requests_used', models.IntegerField(default=0)),
                ('total_upserted', models.IntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places_seed_state',
            },
        ),
        migrations.AddIndex(
            model_name='placesseed',
            index=models.Index(fields=['pref_code', 'label'], name='places_seed_pref_co_27f61e_idx'),
        ),
        migrations.AddIndex(
            model_name='placesseed',
            index=models.Index(fields=['is_active', 'updated_at'], name='places_seed_is_acti_04817c_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondatabootstraprun',
            index=models.Index(fields=['status', 'updated_at'], name='idx_bootstrap_status_updated'),
        ),
        migrations.AddIndex(
            model_name='productiondatabootstraprun',
            index=models.Index(fields=['step', 'version'], name='idx_bootstrap_step_version'),
        ),
        migrations.AddConstraint(
            model_name='productiondatabootstraprun',
            constraint=models.UniqueConstraint(fields=('step', 'version'), name='uniq_production_bootstrap_step_version'),
        ),
        migrations.AddField(
            model_name='rankinglog',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_logs', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='shrinedeity',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deities', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='shrinehistory',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='shrineinteractionlog',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='shrineinteractionlog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shrine_interaction_logs', to='temples.conciergethread'),
        ),
        migrations.AddField(
            model_name='shrineinteractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrine_interaction_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shrinehistory',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='histories', to='temples.shrineknowledgesource'),
        ),
        migrations.AddField(
            model_name='shrinedeity',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='deities', to='temples.shrineknowledgesource'),
        ),
        migrations.AddField(
            model_name='shrinereflection',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='temples.shrine'),
        ),
        migrations.AddField(
            model_name='shrinereflection',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='振り返り対象の参拝のきっかけとなった相談スレッド（Recommendation Snapshotへの接続キー）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='temples.conciergethread'),
        ),
        migrations.AddField(
            model_name='shrinereflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrine_reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shrinesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shrine_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shrinesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrine_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ShrineDeities',
        ),
        migrations.AddIndex(
            model_name='actionevent',
            index=models.Index(fields=['user', 'action_type'], name='idx_action_user_type'),
        ),
        migrations.AddIndex(
            model_name='actionevent',
            index=models.Index(fields=['user', '-created_at'], name='idx_action_user_created'),
        ),
        migrations.AddIndex(
            model_name='actionevent',
            index=models.Index(fields=['history_theme', 'action_type'], name='idx_action_theme_type'),
        ),
        migrations.AddIndex(
            model_name='actionevent',
            index=models.Index(fields=['action_suggestion_id', 'action_type'], name='idx_action_suggestion_type'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='idx_fav_user_created'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('shrine__isnull', False)), fields=('user', 'shrine'), name='uniq_favorite_user_shrine'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('place_id__isnull', False)), fields=('user', 'place_id'), name='uniq_favorite_user_place'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shrine__isnull', False), ('place_id__isnull', True)), models.Q(('shrine__isnull', True), ('place_id__isnull', False)), _connector='OR'), name='chk_favorite_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['scope', 'feature'], name='temples_fea_scope_16bb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['user', 'feature'], name='temples_fea_user_id_ed3ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['anon_id', 'feature'], name='temples_fea_anon_id_6f0176_idx'),
        ),
        migrations.AddConstraint(
            model_name='featureusage',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'user'), ('user__isnull', False)), fields=('user', 'feature'), name='uq_feature_usage_user_feature'),
        ),
        migrations.AddConstraint(
            model_name='featureusage',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'anonymous'), ('anon_id__gt', '')), fields=('anon_id', 'feature'), name='uq_feature_usage_anon_feature'),
        ),
        migrations.AddConstraint(
            model_name='featureusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'user'), ('user__isnull', False), ('anon_id', '')), models.Q(('scope', 'anonymous'), ('user__isnull', True), ('anon_id__gt', '')), _connector='OR'), name='chk_feature_usage_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('shrine', 'user'), name='uq_like_shrine_user'),
        ),
        migrations.AddIndex(
            model_name='placesseedstate',
            index=models.Index(fields=['last_status', 'last_run_at'], name='places_seed_last_st_b771ca_idx'),
        ),
        migrations.AddIndex(
            model_name='placesseedstate',
            index=models.Index(fields=['cooldown_until'], name='places_seed_cooldow_b4ea36_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankinglog',
            constraint=models.UniqueConstraint(fields=('shrine', 'date'), name='uq_rankinglog_shrine_date'),
        ),
        migrations.AddIndex(
            model_name='shrineinteractionlog',
            index=models.Index(fields=['user', 'shrine', 'action_type'], name='idx_interact_user_shrine_act'),
        ),
        migrations.AddIndex(
            model_name='shrineinteractionlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_interaction_user_created'),
        ),
        migrations.AddIndex(
            model_name='shrineinteractionlog',
            index=models.Index(fields=['shrine', '-created_at'], name='idx_interaction_shrine_created'),
        ),
        migrations.AddIndex(
            model_name='shrinehistory',
            index=models.Index(fields=['shrine', 'sort_order'], name='idx_shrine_history_sort'),
        ),
        migrations.AddIndex(
            model_name='shrinedeity',
            index=models.Index(fields=['shrine', 'sort_order'], name='idx_shrine_deity_sort'),
        ),
        migrations.AddIndex(
            model_name='shrinereflection',
            index=models.Index(fields=['user', '-created_at'], name='idx_reflection_user_created'),
        ),
        migrations.AddIndex(
            model_name='shrinereflection',
            index=models.Index(fields=['shrine', '-created_at'], name='idx_reflection_shrine_created'),
        ),
        migrations.AddIndex(
            model_name='shrinereflection',
            index=models.Index(fields=['history_theme'], name='idx_reflection_history_theme'),
        ),
        migrations.AddIndex(
            model_name='shrinesubmission',
            index=models.Index(fields=['status', 'created_at'], name='idx_submission_status_created'),
        ),
        migrations.AddIndex(
            model_name='shrinesubmission',
            index=models.Index(fields=['user', 'created_at'], name='idx_submission_user_created'),
        ),
        migrations.AddConstraint(
            model_name='shrinesubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', True), ('lng__isnull', True)), models.Q(('lat__isnull', False), ('lng__isnull', False)), _connector='OR'), name='chk_submission_lat_lng_both_or_none'),
        ),
    ]
