# Generated by Django 5.2.16 on 2026-09-04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0010_shrinegoriyakuassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rationale", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "goriyaku_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="temples.shrinegoriyakuassignment",
                    ),
                ),
                (
                    "history_theme_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="temples.historythemeassignment",
                    ),
                ),
                (
                    "shrine_deity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="temples.shrinedeity",
                    ),
                ),
                (
                    "shrine_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="temples.shrinehistory",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("goriyaku_assignment__isnull", True),
                            ("history_theme_assignment__isnull", False),
                        )
                        | models.Q(
                            ("goriyaku_assignment__isnull", False),
                            ("history_theme_assignment__isnull", True),
                        ),
                        name="chk_evlink_one_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("shrine_deity__isnull", True),
                            ("shrine_history__isnull", False),
                        )
                        | models.Q(
                            ("shrine_deity__isnull", False),
                            ("shrine_history__isnull", True),
                        ),
                        name="chk_evlink_one_fact",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rationale", ""), _negated=True),
                        name="chk_evlink_rationale_nonempty",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("history_theme_assignment__isnull", False),
                            ("shrine_history__isnull", False),
                        ),
                        fields=("history_theme_assignment", "shrine_history"),
                        name="uniq_evlink_ht_history",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("history_theme_assignment__isnull", False),
                            ("shrine_deity__isnull", False),
                        ),
                        fields=("history_theme_assignment", "shrine_deity"),
                        name="uniq_evlink_ht_deity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("goriyaku_assignment__isnull", False),
                            ("shrine_history__isnull", False),
                        ),
                        fields=("goriyaku_assignment", "shrine_history"),
                        name="uniq_evlink_gori_history",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("goriyaku_assignment__isnull", False),
                            ("shrine_deity__isnull", False),
                        ),
                        fields=("goriyaku_assignment", "shrine_deity"),
                        name="uniq_evlink_gori_deity",
                    ),
                ],
            },
        ),
    ]
