# Generated by Django 5.2.16 on 2026-09-24 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0013_remove_legacy_temples_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineCanonicalAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "CONFIRMED"),
                            ("HOLD_POSITION_REVIEW", "HOLD_POSITION_REVIEW"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject", models.TextField(blank=True, default="")),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE_PRINCIPAL_UNIT", "SINGLE_PRINCIPAL_UNIT"),
                            ("MULTI_PRINCIPAL_UNIT", "MULTI_PRINCIPAL_UNIT"),
                            ("NON_BUILDING_RITUAL_CENTER", "NON_BUILDING_RITUAL_CENTER"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "point_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_POINT", "DIRECT_POINT"),
                            ("UNWEIGHTED_COMPONENT_MEAN", "UNWEIGHTED_COMPONENT_MEAN"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "component_set_status",
                    models.CharField(
                        blank=True,
                        choices=[("COMPLETE", "COMPLETE"), ("INCOMPLETE", "INCOMPLETE")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shrine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_anchor",
                        to="temples.shrine",
                    ),
                ),
            ],
            options={
                "db_table": "temples_shrine_canonical_anchor",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ShrineCanonicalAnchorComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_attested_name", models.TextField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("INCLUDED", "INCLUDED"),
                            ("EXCLUDED", "EXCLUDED"),
                            ("UNCLASSIFIED", "UNCLASSIFIED"),
                        ],
                        max_length=16,
                    ),
                ),
                ("classification_rationale", models.TextField(blank=True, default="")),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="temples.shrinecanonicalanchor",
                    ),
                ),
            ],
            options={
                "db_table": "temples_shrine_canonical_anchor_component",
                "ordering": ["anchor_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShrineCanonicalAnchorEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "evidence_role",
                    models.CharField(
                        choices=[("SEMANTIC", "SEMANTIC"), ("COORDINATE", "COORDINATE")],
                        max_length=16,
                    ),
                ),
                ("source_type", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.TextField(blank=True, default="")),
                ("publisher", models.TextField(blank=True, default="")),
                ("url", models.CharField(blank=True, default="", max_length=2048)),
                ("accessed_at", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("extraction_method", models.TextField(blank=True, default="")),
                ("evidence_strength", models.CharField(blank=True, default="", max_length=64)),
                ("stated_precision", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="temples.shrinecanonicalanchor",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="evidences",
                        to="temples.shrinecanonicalanchorcomponent",
                    ),
                ),
            ],
            options={
                "db_table": "temples_shrine_canonical_anchor_evidence",
                "ordering": ["anchor_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("CONFIRMED", "HOLD_POSITION_REVIEW"))),
                name="chk_canon_anchor_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subject_type__isnull", True),
                    (
                        "subject_type__in",
                        (
                            "SINGLE_PRINCIPAL_UNIT",
                            "MULTI_PRINCIPAL_UNIT",
                            "NON_BUILDING_RITUAL_CENTER",
                        ),
                    ),
                    _connector="OR",
                ),
                name="chk_canon_anchor_subject_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("point_method__isnull", True),
                    ("point_method__in", ("DIRECT_POINT", "UNWEIGHTED_COMPONENT_MEAN")),
                    _connector="OR",
                ),
                name="chk_canon_anchor_point_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("component_set_status__isnull", True),
                    ("component_set_status__in", ("COMPLETE", "INCOMPLETE")),
                    _connector="OR",
                ),
                name="chk_canon_anchor_component_set_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="chk_canon_anchor_lat_lng_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90.0), ("latitude__lte", 90.0)),
                name="chk_canon_anchor_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180.0), ("longitude__lte", 180.0)),
                name="chk_canon_anchor_lng_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "HOLD_POSITION_REVIEW"), _negated=True),
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    _connector="OR",
                ),
                name="chk_canon_anchor_hold_no_coordinate",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "CONFIRMED"), _negated=True),
                    models.Q(
                        models.Q(("subject", ""), _negated=True),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("point_method__isnull", False),
                        ("subject_type__isnull", False),
                        ("verified_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_canon_anchor_confirmed_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("component_set_status", "INCOMPLETE"), ("status", "CONFIRMED"), _negated=True
                ),
                name="chk_canon_anchor_confirmed_not_incomplete",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("point_method", "UNWEIGHTED_COMPONENT_MEAN"),
                        ("status", "CONFIRMED"),
                        ("subject_type", "MULTI_PRINCIPAL_UNIT"),
                        _negated=True,
                    ),
                    models.Q(
                        ("component_set_status", "COMPLETE"),
                        ("component_set_status__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_canon_anchor_multi_mean_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("classification__in", ("INCLUDED", "EXCLUDED", "UNCLASSIFIED"))
                ),
                name="chk_canon_component_classification",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_attested_name", ""), _negated=True),
                name="chk_canon_component_name_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="chk_canon_component_lat_lng_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90.0), ("latitude__lte", 90.0)),
                name="chk_canon_component_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180.0), ("longitude__lte", 180.0)),
                name="chk_canon_component_lng_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("classification", "INCLUDED"),
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    _connector="OR",
                ),
                name="chk_canon_component_coord_included_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrinecanonicalanchorevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("evidence_role__in", ("SEMANTIC", "COORDINATE"))),
                name="chk_canon_evidence_role",
            ),
        ),
    ]
