# Generated by Django 5.2.16 on 2026-10-04 09:44

import django.db.models.deletion
import django.utils.timezone
import temples.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0018_collective_runtime_activation_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineSourceFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stable_key",
                    models.CharField(
                        max_length=255, unique=True, validators=[temples.models._validate_not_blank]
                    ),
                ),
                (
                    "source_attested_wording",
                    models.CharField(
                        max_length=255, validators=[temples.models._validate_not_blank]
                    ),
                ),
                (
                    "evidence_characterization",
                    models.CharField(
                        choices=[
                            ("official_prayer_supported", "official_prayer_supported"),
                            (
                                "official_current_guidance_supported",
                                "official_current_guidance_supported",
                            ),
                            (
                                "official_prayer_and_current_guidance_list_level",
                                "official_prayer_and_current_guidance_list_level",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("unverified", "unverified"),
                            ("source_confirmed", "source_confirmed"),
                            ("reviewed", "reviewed"),
                            ("disputed", "disputed"),
                            ("outdated", "outdated"),
                            ("rejected", "rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_facts",
                        to="temples.shrine",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="source_facts", to="temples.shrineknowledgesource"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("stable_key__regex", "\\S")),
                        name="chk_source_fact_stable_key_not_blank",
                    )
                ],
            },
        ),
    ]
