import * as React from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { get } from "../lib/http";
import { kamimusubiDark as theme } from "../app/theme";
import { ProfilePickerModal } from "./profile/ProfilePickerModal";
import { PREFECTURE_ORIGINS, prefectureOrigin, type OriginMode, type UserOrigin } from "../../../packages/shared/userOrigin";

type Candidate={place_id:string;name:string|null;lat:number;lng:number;type?:string};
export function MobileOriginSelector({origin,onChange,onUseDevice,locationStatus="idle",disabled}: {origin:UserOrigin|null;onChange:(value:UserOrigin|null)=>void;onUseDevice:()=>void;locationStatus?:"idle"|"loading"|"ready"|"error";disabled?:boolean}){
  const [mode,setMode]=React.useState<OriginMode>(origin?.source==="device"?"device":origin?.source==="prefecture"?"prefecture":origin?"manual":"none");
  const [query,setQuery]=React.useState("");const [items,setItems]=React.useState<Candidate[]>([]);const [status,setStatus]=React.useState<"idle"|"searching"|"empty"|"error">("idle");const [picker,setPicker]=React.useState(false);const requestId=React.useRef(0);
  React.useEffect(()=>{if(mode!=="manual"||query.trim().length<2){setItems([]);setStatus("idle");return;}const id=++requestId.current;const timer=setTimeout(async()=>{setStatus("searching");try{const data=await get<{items?:Candidate[]}>(`/geocodes/search/?q=${encodeURIComponent(query.trim())}&limit=5&lang=ja`);if(id!==requestId.current)return;const next=Array.isArray(data.items)?data.items:[];setItems(next);setStatus(next.length?"idle":"empty");}catch{if(id===requestId.current){setItems([]);setStatus("error");}}},400);return()=>clearTimeout(timer);},[mode,query]);
  const switchMode=(next:OriginMode)=>{requestId.current++;setMode(next);onChange(null);setItems([]);if(next==="device")onUseDevice();};
  return <View style={s.wrap}><View style={s.row}>{[["device","現在地を使用"],["manual","駅名・住所から指定"],["prefecture","都道府県から指定"],["disabled","方位情報を使用しない"]].map(([value,label])=><Pressable disabled={disabled} key={value} onPress={()=>switchMode(value as OriginMode)} style={[s.button,mode===value&&s.active]}><Text style={s.text}>{label}</Text></Pressable>)}</View>
  {mode==="manual"?<><TextInput accessibilityLabel="駅名または住所" value={query} onChangeText={value=>{setQuery(value);onChange(null);}} placeholder="駅名または住所を入力" placeholderTextColor={theme.mutedDark} style={s.input}/>{status==="searching"?<Text style={s.note}>検索中…</Text>:null}{status==="empty"?<Text style={s.note}>候補が見つかりません。相談は続けられます。</Text>:null}{status==="error"?<Text style={s.error}>検索できませんでした。相談は続けられます。</Text>:null}{items.map(item=><Pressable key={item.place_id} onPress={()=>{onChange({latitude:item.lat,longitude:item.lng,source:item.type==="station"?"station":"address",displayName:item.name??query,accuracy:"precise"});setItems([]);}} style={s.result}><Text style={s.text}>{item.name}</Text></Pressable>)}</>:null}
  {mode==="prefecture"?<><Pressable onPress={()=>setPicker(true)} style={s.input}><Text style={s.text}>{origin?.source==="prefecture"?origin.displayName:"都道府県を選択"}</Text></Pressable>{origin?.source==="prefecture"?<Text style={s.note}>{origin.displayName}のおおよその位置を出発地点として使用します。方位は参考情報です。</Text>:null}</>:null}
  {mode==="device"&&locationStatus==="loading"?<Text style={s.note}>現在地を取得中…</Text>:null}{mode==="device"&&locationStatus==="error"?<Text style={s.error}>現在地を取得できませんでした。手動入力を選択できます。</Text>:null}{origin?<Text style={s.selected}>設定中：{origin.displayName??"現在地"}</Text>:null}
  <ProfilePickerModal visible={picker} title="都道府県" options={PREFECTURE_ORIGINS.map(p=>({value:p.name,label:p.name}))} selectedValue={origin?.source==="prefecture"?origin.displayName:undefined} onClose={()=>setPicker(false)} onSelect={value=>{onChange(prefectureOrigin(value));setPicker(false);}} /></View>;
}
const s=StyleSheet.create({wrap:{gap:8},row:{flexDirection:"row",flexWrap:"wrap",gap:6},button:{borderWidth:1,borderColor:theme.borderSoft,borderRadius:12,padding:8},active:{borderColor:theme.goldSoft,backgroundColor:theme.surfaceSoft},text:{color:theme.text,fontSize:12},input:{borderWidth:1,borderColor:theme.borderSoft,borderRadius:12,padding:10,color:theme.text},result:{padding:10,borderBottomWidth:1,borderBottomColor:theme.borderSoft},note:{color:theme.muted,fontSize:11,lineHeight:17},error:{color:"#fca5a5",fontSize:11},selected:{color:theme.goldSoft,fontSize:11}});
