# Generated by Django 5.2.13 on 2026-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0079_shrinesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrine",
            name="visit_style_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="参拝スタイルタグ: ['quiet','nature','classic'] など",
            ),
        ),
    ]
