from django.db import migrations

SQL = """
CREATE TABLE IF NOT EXISTS temples_featureusage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope varchar(16) NOT NULL,
    anon_id varchar(64) NOT NULL DEFAULT '',
    feature varchar(32) NOT NULL,
    count integer NOT NULL DEFAULT 0 CHECK (count >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    user_id bigint NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT chk_feature_usage_scope_target CHECK (
        (scope = 'user' AND user_id IS NOT NULL AND anon_id = '')
        OR
        (scope = 'anonymous' AND user_id IS NULL AND anon_id > '')
    )
);
CREATE INDEX IF NOT EXISTS temples_fea_scope_16bb7d_idx ON temples_featureusage (scope, feature);
CREATE INDEX IF NOT EXISTS temples_fea_user_id_ed3ce9_idx ON temples_featureusage (user_id, feature);
CREATE INDEX IF NOT EXISTS temples_fea_anon_id_6f0176_idx ON temples_featureusage (anon_id, feature);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_user_feature ON temples_featureusage (user_id, feature) WHERE scope = 'user' AND user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_anon_feature ON temples_featureusage (anon_id, feature) WHERE scope = 'anonymous' AND anon_id > '';
"""

class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0080_shrine_visit_style_tags"),
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
    ]
