from django.db import migrations

def create_featureusage_table(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS temples_featureusage (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scope varchar(16) NOT NULL,
            anon_id varchar(64) NOT NULL DEFAULT '',
            feature varchar(32) NOT NULL,
            count integer NOT NULL DEFAULT 0 CHECK (count >= 0),
            created_at timestamp with time zone NOT NULL DEFAULT NOW(),
            updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
            user_id bigint NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT chk_feature_usage_scope_target CHECK (
                (scope = 'user' AND user_id IS NOT NULL AND anon_id = '')
                OR
                (scope = 'anonymous' AND user_id IS NULL AND anon_id > '')
            )
        );
        """)
        cursor.execute("CREATE INDEX IF NOT EXISTS temples_fea_scope_16bb7d_idx ON temples_featureusage (scope, feature);")
        cursor.execute("CREATE INDEX IF NOT EXISTS temples_fea_user_id_ed3ce9_idx ON temples_featureusage (user_id, feature);")
        cursor.execute("CREATE INDEX IF NOT EXISTS temples_fea_anon_id_6f0176_idx ON temples_featureusage (anon_id, feature);")
        cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_user_feature ON temples_featureusage (user_id, feature) WHERE scope = 'user' AND user_id IS NOT NULL;")
        cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_usage_anon_feature ON temples_featureusage (anon_id, feature) WHERE scope = 'anonymous' AND anon_id > '';")
        cursor.execute("SELECT to_regclass('public.temples_featureusage');")
        print("[repair] temples_featureusage =", cursor.fetchone()[0])

class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0081_recreate_featureusage_if_missing"),
    ]

    operations = [
        migrations.RunPython(create_featureusage_table, reverse_code=migrations.RunPython.noop),
    ]
