# Generated by Django 5.2.13 on 2026-05-13 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0083_productiondatabootstraprun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shrine",
            name="history_theme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="神社の歴史文脈タグ: 再出発 / 静寂 / 復興 / 勝負 / 縁 / 学び / 守り",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["history_theme"], name="idx_shrine_history_theme"),
        ),
    ]
