# Generated by Django 5.2.13 on 2026-05-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0084_shrine_history_theme_shrine_idx_shrine_history_theme"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS temples_favorite (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                shrine_id bigint NULL REFERENCES temples_shrine(id) DEFERRABLE INITIALLY DEFERRED,
                place_id varchar(128) NULL,
                created_at timestamptz NOT NULL DEFAULT NOW(),
                CONSTRAINT chk_favorite_exactly_one_target CHECK (
                    (shrine_id IS NOT NULL AND place_id IS NULL)
                    OR
                    (shrine_id IS NULL AND place_id IS NOT NULL)
                )
            );

            CREATE UNIQUE INDEX IF NOT EXISTS uniq_favorite_user_shrine
            ON temples_favorite(user_id, shrine_id)
            WHERE shrine_id IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS uniq_favorite_user_place
            ON temples_favorite(user_id, place_id)
            WHERE place_id IS NOT NULL;

            CREATE INDEX IF NOT EXISTS temples_favorite_place_id_idx
            ON temples_favorite(place_id);

            CREATE INDEX IF NOT EXISTS idx_fav_user_created
            ON temples_favorite(user_id, created_at);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
