# Generated by Django 5.2.13 on 2026-06-03 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0086_repair_visit_user_shrine_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "history_theme",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="保存時点の history_theme スナップショット",
                        max_length=32,
                    ),
                ),
                ("prompt", models.TextField(blank=True, default="")),
                ("answer", models.TextField()),
                ("mood_before", models.CharField(blank=True, default="", max_length=50)),
                ("mood_after", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="temples.shrine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shrine_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_reflection_user_created"
                    ),
                    models.Index(
                        fields=["shrine", "-created_at"], name="idx_reflection_shrine_created"
                    ),
                    models.Index(fields=["history_theme"], name="idx_reflection_history_theme"),
                ],
            },
        ),
    ]
