# Generated by Django 5.2.13 on 2026-06-05 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0087_shrinereflection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("detail_view", "Detail view"),
                            ("route_open", "Route open"),
                            ("shrine_card_click", "Shrine card click"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_logs",
                        to="temples.shrine",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shrine_interaction_logs",
                        to="temples.conciergethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shrine_interaction_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "shrine", "action_type"],
                        name="idx_interact_user_shrine_act",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="idx_interaction_user_created"
                    ),
                    models.Index(
                        fields=["shrine", "-created_at"], name="idx_interaction_shrine_created"
                    ),
                ],
            },
        ),
    ]
