# Generated by Django 5.2.13 on 2026-06-06 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0088_shrineinteractionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("action_started", "Action started"),
                            ("action_completed", "Action completed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("action_suggestion_id", models.CharField(db_index=True, max_length=128)),
                (
                    "history_theme",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                (
                    "action_category",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                ("source", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shrine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_events",
                        to="temples.shrine",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_events",
                        to="temples.conciergethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "action_type"], name="idx_action_user_type"),
                    models.Index(fields=["user", "-created_at"], name="idx_action_user_created"),
                    models.Index(
                        fields=["history_theme", "action_type"], name="idx_action_theme_type"
                    ),
                    models.Index(
                        fields=["action_suggestion_id", "action_type"],
                        name="idx_action_suggestion_type",
                    ),
                ],
            },
        ),
    ]
