# Generated by Django 5.2.8 on 2026-07-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0091_fill_missing_local_shrine_reason_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrinereflection",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                help_text="振り返り対象の参拝のきっかけとなった相談スレッド（Recommendation Snapshotへの接続キー）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reflections",
                to="temples.conciergethread",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                help_text="参拝のきっかけとなった相談スレッド（Recommendation Snapshotへの接続キー）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="temples.conciergethread",
            ),
        ),
    ]
