# Generated by Django 5.2.8 on 2026-07-31 05:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import temples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0092_add_thread_to_visit_and_reflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrineKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('shrine_official', 'shrine_official'), ('government', 'government'), ('cultural_property', 'cultural_property'), ('academic', 'academic'), ('museum_or_archive', 'museum_or_archive'), ('local_history', 'local_history'), ('tourism_official', 'tourism_official'), ('secondary_editorial', 'secondary_editorial'), ('user_observation', 'user_observation'), ('internal_research', 'internal_research')], max_length=32)),
                ('title', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('bibliography', models.TextField(blank=True, default='')),
                ('accessed_at', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShrineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('official_origin', 'official_origin'), ('founding', 'founding'), ('historical_event', 'historical_event'), ('tradition', 'tradition'), ('regional_context', 'regional_context'), ('editorial_summary', 'editorial_summary')], max_length=32)),
                ('title', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('content', models.TextField(validators=[temples.models._validate_not_blank])),
                ('period_text', models.CharField(blank=True, default='', help_text='推定年代等、幅を持つ期間表現（例: 8世紀頃）。確定日はevent_dateを使う。', max_length=255)),
                ('event_date', models.DateField(blank=True, help_text='確定している場合のみ設定する。', null=True)),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='temples.shrine')),
                ('sources', models.ManyToManyField(blank=True, related_name='histories', to='temples.shrineknowledgesource')),
            ],
            options={
                'verbose_name_plural': 'Shrine histories',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['shrine', 'sort_order'], name='idx_shrine_history_sort')],
            },
        ),
        migrations.CreateModel(
            name='ShrineDeity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, validators=[temples.models._validate_not_blank])),
                ('canonical_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('primary', 'primary'), ('enshrined', 'enshrined'), ('secondary', 'secondary'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verification_status', models.CharField(choices=[('draft', 'draft'), ('unverified', 'unverified'), ('source_confirmed', 'source_confirmed'), ('reviewed', 'reviewed'), ('disputed', 'disputed'), ('outdated', 'outdated'), ('rejected', 'rejected')], default='draft', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=8)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deities', to='temples.shrine')),
                ('sources', models.ManyToManyField(blank=True, related_name='deities', to='temples.shrineknowledgesource')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['shrine', 'sort_order'], name='idx_shrine_deity_sort')],
            },
        ),
    ]
