# Generated by Django 5.2.16 on 2026-09-02 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0102_history_theme_assignment_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineGoriyakuAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        help_text="Evidence Foundation canonical semantic key（例: goriyaku:<stable_key>）。既存GoriyakuTag.nameとは別の、機械識別子。PR-F3時点では承認済みkeyが存在しないため、いかなる値も現時点ではvalidationを通過しない。",
                        max_length=64,
                    ),
                ),
                (
                    "taxonomy_version",
                    models.CharField(
                        help_text='canonical_keyがどのgoriyaku taxonomy versionで解釈されるか（Mother Ship FINAL contract: 文字列表現、例 "v1"）。',
                        max_length=8,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("REVOKED", "REVOKED")], max_length=16
                    ),
                ),
                (
                    "producer",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("curator", "curator"),
                            ("migration", "migration"),
                            ("verified_import", "verified_import"),
                            ("controlled_automation", "controlled_automation"),
                        ],
                        help_text="PR-F1 evidence_provenance.EVIDENCE_PRODUCERSをそのまま再利用。",
                        max_length=32,
                    ),
                ),
                (
                    "mechanism",
                    models.CharField(
                        choices=[
                            ("manual_review", "manual_review"),
                            ("source_backed_import", "source_backed_import"),
                            ("verified_migration", "verified_migration"),
                            ("controlled_rule", "controlled_rule"),
                        ],
                        help_text="PR-F1 evidence_provenance.EVIDENCE_MECHANISMSをそのまま再利用。",
                        max_length=32,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        help_text="provenanceに基づく、実際にsemantic assignmentが行われた時刻。created_at（DB行の作成時刻）とは責務が異なり、呼び出し側が明示的に指定する。"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goriyaku_assignments",
                        to="temples.shrine",
                    ),
                ),
            ],
            options={
                "ordering": ["shrine_id", "canonical_key", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("lifecycle", "ACTIVE")),
                        fields=("shrine", "canonical_key", "taxonomy_version"),
                        name="uniq_goriyaku_assignment_active_per_shrine_tag_version",
                    )
                ],
            },
        ),
    ]
