# Generated by Django 5.2.16 on 2026-09-26 12:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import temples.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0115_canonical_anchor_schema_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineDeityCollective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_attested_label",
                    models.CharField(
                        max_length=255, validators=[temples.models._validate_not_blank]
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "primary"),
                            ("enshrined", "enshrined"),
                            ("secondary", "secondary"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("member_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "member_count_relation",
                    models.CharField(
                        choices=[
                            ("exact", "exact"),
                            ("minimum", "minimum"),
                            ("approximate", "approximate"),
                            ("unspecified", "unspecified"),
                        ],
                        default="unspecified",
                        max_length=16,
                    ),
                ),
                (
                    "member_list_status",
                    models.CharField(
                        choices=[
                            ("complete", "complete"),
                            ("partial", "partial"),
                            ("not_enumerated", "not_enumerated"),
                            ("not_determined", "not_determined"),
                        ],
                        default="not_determined",
                        max_length=16,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("unverified", "unverified"),
                            ("source_confirmed", "source_confirmed"),
                            ("reviewed", "reviewed"),
                            ("disputed", "disputed"),
                            ("outdated", "outdated"),
                            ("rejected", "rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deity_collectives",
                        to="temples.shrine",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deity_collectives",
                        to="temples.shrineknowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["shrine", "sort_order"], name="idx_shrine_deity_coll_sort")
                ],
            },
        ),
    ]
