# Generated by Django 5.2.16 on 2026-09-26 12:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0116_shrine_deity_collective_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineDeityCollectiveMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("unverified", "unverified"),
                            ("source_confirmed", "source_confirmed"),
                            ("reviewed", "reviewed"),
                            ("disputed", "disputed"),
                            ("outdated", "outdated"),
                            ("rejected", "rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="temples.shrinedeitycollective",
                    ),
                ),
                (
                    "deity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collective_memberships",
                        to="temples.shrinedeity",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deity_collective_memberships",
                        to="temples.shrineknowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["collective", "sort_order"], name="idx_deity_coll_member_sort"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collective", "deity"), name="uniq_deity_coll_member"
                    )
                ],
            },
        ),
    ]
