# Generated by Django 5.2.16 on 2026-09-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0117_shrine_deity_collective_membership_foundation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shrinedeitycollective",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("member_count__isnull", False),
                        ("member_count_relation__in", ("exact", "minimum", "approximate")),
                    ),
                    models.Q(
                        ("member_count__isnull", True), ("member_count_relation", "unspecified")
                    ),
                    _connector="OR",
                ),
                name="chk_deity_coll_count_rel",
            ),
        ),
    ]
