# Generated by Django 5.2.16 on 2026-09-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0118_shrine_deity_collective_count_relation_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectiveRuntimeActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collective",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_activation",
                        to="temples.shrinedeitycollective",
                    ),
                ),
            ],
        ),
    ]
